# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  workingDirectory: BankApp/BankApp.WebClient
  displayName: 'Install dependencies'

- script: |
    npm install
    npm run lint
  workingDirectory: BankApp/BankApp.WebClient
  displayName: 'Run eslint'

- script: |
    npm run test-no-watch
  workingDirectory: BankApp/BankApp.WebClient
  displayName: 'Run tests'

- script: |
    npm run build
  workingDirectory: BankApp/BankApp.WebClient
  displayName: 'Run build'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/BankApp/BankApp.WebClient/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'